let strip = neopixel.create(DigitalPin.P0, 2, NeoPixelMode.RGB_RGB)
strip.setBrightness(80)
basic.forever(function () {
    strip.showColor(neopixel.colors(NeoPixelColors.Red))
    basic.pause(800)
    strip.showColor(neopixel.colors(NeoPixelColors.Blue))
    basic.pause(800)
    strip.showColor(neopixel.colors(NeoPixelColors.Green))
    basic.pause(800)
    strip.showColor(neopixel.colors(NeoPixelColors.Blue))
    basic.pause(800)
    strip.showColor(neopixel.colors(NeoPixelColors.Black))
    basic.pause(2000)
})
